# Generated by Django 5.2.11 on 2026-03-10 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, max_length=100)),
                ('design_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(default='Custom Yard Sign', max_length=255)),
                ('front_json', models.TextField()),
                ('back_json', models.TextField(blank=True, null=True)),
                ('preview_front', models.ImageField(upload_to='designs/previews/')),
                ('preview_back', models.ImageField(blank=True, null=True, upload_to='designs/previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AnonymousDesign',
        ),
    ]
