# Generated by Django 5.2.11 on 2026-03-10 09:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userdesign_delete_anonymousdesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, max_length=100)),
                ('design_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(default='My Custom Sign', max_length=255)),
                ('design_json', models.TextField()),
                ('preview_image', models.ImageField(upload_to='design_previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserDesign',
        ),
    ]
