# Generated by Django 5.2.11 on 2026-03-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_anonymousdesign_delete_userdesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_preview', models.ImageField(upload_to='custom_designs/')),
                ('size', models.CharField(max_length=50)),
                ('sides', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=50)),
                ('finishing', models.CharField(max_length=50)),
                ('mounting', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
