# Generated by Django 5.2.11 on 2026-03-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='visitor_id',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
